### ISSUE TITLE
import additional oncogenic evidence from oncokb

### ISSUE THREAD

**Issue by bwalsh** [ohsu-comp-bio/g2p-aggregator#19]
We have already imported evidence pmkb & civic that associates location with disease. (no drug)
We should do the same with oncokb

**Comment by jgoecks** [comment]
We should also import oncogenic evidence for CGI: https://www.cancergenomeinterpreter.org/mutations

**Comment by ahwagner** [comment]
I see this as "in progress" in v0.4. Who is working on this issue?

**Comment by grmayfie** [comment]
There are sort of two parts to this issue, importing oncogenic evidence from oncokb and importing from CGI. 

I was working on the import from oncokb a few weeks ago, but the work was halted due to some confusion as to whether or not it really needed to be done, such as brought up in issue 30. To my knowledge, no effort has occurred at all on the CGI front part. 

@jgoecks, do I have official say-so that this should be moving forward in this sprint, according to the conversation in issue 30?

**Comment by jgoecks** [comment]
@mayfielg Yes, please move forward with importing oncogenic mutations from all available sources into the database based on the conversation in #30.

**Comment by bwalsh** [comment]
should this be closed based on GM's oncokb import?

**Comment by grmayfie** [comment]
@bwalsh Bringing in additional CGI variants was also brought up in this issue. I think we should wither leave it open until that task is handled, or close it and create a new issue for CGI additional variants specifically. I have no real preference on either option, just don't want to lose that task. Which would you prefer?

**Comment by bwalsh** [comment]
@mayfielg  I would close it and create a new task for CGI.
