### ISSUE TITLE
Review oncokb harvester counts 

### ISSUE THREAD

**Issue by bwalsh** [ohsu-comp-bio/g2p-aggregator#30]
currently ~ 300+ evidence items, should be much higher

**Comment by bwalsh** [comment]
Right now, we are only pulling from clinical endpoint.
'http://oncokb.org/api/private/search/variants/clinical?hugoSymbol={}' 
Should we be looking at this instead or in addition to?
'http://oncokb.org/api/private/search/variants/biological?hugoSymbol={}'

**Comment by bwalsh** [comment]
related to #19

**Comment by jgoecks** [comment]
I'm not sure about this endpoint, but we should be pulling in oncogenic mutations from all sources, including oncokb.

**Comment by ahwagner** [comment]
I spoke with Debyani about the data at OncoKB, and we'll want to retrieve both actionable and annotated variants for our purposes. Looking at the available endpoints, the `/utils/allActionableVariants` and `/utils/allAnnotatedVariants` endpoints seem to contain the information we need, and we would process the response from the latter without an evidence level.

**Comment by jgoecks** [comment]
@ahwagner Do we really want the annotated variants in the database? The only information associated with these variants is is `Neutral\Likely Neutral\Likely Oncogenic\Oncogenic` and `Loss/Gain of Function`— this phenotypic information is very different than drug associations.

**Comment by ahwagner** [comment]
Yes, I agree that these data would not fit into many of the analyses we are doing. These certainly aren't evidence items with drug information, and the phenotype wouldn't be a disease exactly. However, if we had no other information on a variant (a clinical interpretation or disease context), wouldn't it still be nice to know if it were oncogenic?

We are including variants that are prognostic, diagnostic, and predisposing (germline) from CIViC, alongside all of the entries from PMKB (which lack drug info and evidence levels), so we haven't been limiting ourselves to predictive entries only.

I suppose that the one difference here is that there is no disease context, which is present in our other harvested claims (though not always normalized).

**Comment by obigriffith** [comment]
Yeah. I tend to agree that we should pull these variants in, just to comprehensively represent oncoKB. But variants of biological significance only should be considered as a lower priority and a separate from those of clinical significance. This kind of association is something we also want to add to CIViC so in the future we would also be able to intersect between knowledgebases on biological function. Also, we should keep in mind that this is not just any biological function. These are variants that oncoKB curators believe have evidence for gain or loss of function in oncogenes or tumor suppressors. This is still a narrow definition of biological function with relevance to the problem of precision medicine in cancer. In the absence of any more established clinical evidence, knowing that a patient has a variant thought to be oncogenic may still have some utility.

**Comment by ahwagner** [comment]
This seems like a good opportunity to consider tagging harvested variants by type (i.e. 'Predictive', 'Prognostic', 'Diagnostic', 'Predisposing', 'Biological Function'), to help delineate these types of entities. It would also enable us to pull in other resources down the road that have relevant variant-phenotype associations that aren't clinical interpretations.

**Comment by malachig** [comment]
I think we should try to include these.  As ahwagner says, we are already pulling in other categories from CIViC.

Looking at this page in OncoKB:
http://oncokb.org/#/actionableGenes

I see 91+94+71+64 = 320 variants with disease, drugs, and evidence associated.  From that the current yield of ~300 sounds reasonably.

However, note that there are several cases where the "variant" in OncoKB is "Oncogenic Mutations".   They document how oncogenic mutations of a particular gene predict response to a particular drug in a particular cancer type.  They then treat it as an independent problem to document which specific variants have evidence for oncogenicity.  Thus "Oncogenic Mutations" is really a place holder for, in some cases a large list of specific variants that could be predicted to respond to the drug.  There is an extra step, but one could expand out disease-drug-variant relationships where we have evidence a variant is oncogenic.  The evidence for each specific oncogenic variant is indirect, so I would definitely consider it less established and more speculative.  One of the things I like about OncoKB is that they are addressing this part of the problem:  

Variants A,B in oncogene X have been demonstrated to predict response to drug Y.  A new patient has variant C.  We haven't previously treated a patient with variant C and observed a response, but we have functional evidence that variant C is oncogenic.  Therefore it might be expected to respond to drug Y as well.  

This is particularly useful for cases where inactivation of a gene predicts response to a drug.  There are so many ways to inactivate a gene that the list of actionable variants gets large fast.  But not every variant is inactivating.  So you need to document them one by one.  Establishing their function is not fun, but easier then definitively establishing their clinical relevance.  In an ideal world you would have clinical trial data for every individual variant (and eventually this data will grow).  But for now, you divide the problem in two: document evidence that inactivation of the gene predicts response to therapy, and document which variants appear to result in loss of function.

In CIViC we have considered adding evidence like this as 'Inferential'.  We have generally punted on this since documenting the more established evidence seems higher priority.  But when you are actually sequencing cases and trying to personalize therapy for each case you quickly encounter cases where where this kind of inference comes up.

**Comment by bwalsh** [comment]
should this issue be closed based on GM's oncokb import?

**Comment by grmayfie** [comment]
@bwalsh I think definitely so, yes. Other thoughts, anyone?
